import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

def get_db_connection():
    user = os.getenv("ORACLE_USER")
    password = os.getenv("ORACLE_PASSWORD")
    dsn = os.getenv("ORACLE_DSN")
    
    if not all([user, password, dsn]):
        raise ValueError("Oracle DB connection info is missing in .env")
        
    # oracledb 기본 모드(Thin mode)로 연결
    connection = oracledb.connect(user=user, password=password, dsn=dsn)
    return connection

def setup_database():
    print("Connecting to Oracle DB to setup table...")
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        # 정비 이력 RAG용 테이블 생성 쿼리 (가장 심플한 RDB 방식 - 옵션 B)
        create_table_sql = """
        CREATE TABLE maintenance_history (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pattern_desc VARCHAR2(255),
            temp_mean NUMBER(10, 2),
            vib_mean NUMBER(10, 2),
            cause VARCHAR2(255),
            action_taken VARCHAR2(500),
            success_rate NUMBER(5, 2),
            is_false_alarm NUMBER(1) DEFAULT 0
        )
        """
        
        # 테이블이 존재하는지 확인 후 없으면 생성
        try:
            cursor.execute("SELECT 1 FROM maintenance_history WHERE rownum = 1")
            print("Table 'maintenance_history' already exists.")
        except oracledb.DatabaseError as e:
            error, = e.args
            if error.code == 942: # ORA-00942: table or view does not exist
                print("Table does not exist. Creating...")
                cursor.execute(create_table_sql)
                
                # 초기 샘플 데이터 주입 (Phase 1의 Mock DB)
                insert_sql = """
                INSERT INTO maintenance_history (pattern_desc, temp_mean, vib_mean, cause, action_taken, success_rate, is_false_alarm)
                VALUES (:1, :2, :3, :4, :5, :6, :7)
                """
                sample_data = [
                    ("High temperature and high vibration", 65.0, 1.2, "Bearing wear", "Replace bearing", 0.95, 0),
                    ("High temperature, normal vibration", 60.0, 0.6, "Cooling fan failure", "Check and replace cooling fan", 0.88, 0),
                    ("Normal temperature, high vibration", 50.0, 1.5, "Misalignment", "Realign the shaft", 0.92, 0),
                    ("Short spike in temperature (False Alarm)", 55.0, 0.5, "Sensor Glitch", "Ignore or recalibrate sensor", 0.99, 1)
                ]
                cursor.executemany(insert_sql, sample_data)
                conn.commit()
                print("Table created and sample data inserted.")
            else:
                raise

    except Exception as e:
        print(f"Database setup failed: {e}")
    finally:
        if 'cursor' in locals():
            cursor.close()
        if 'conn' in locals():
            conn.close()

if __name__ == "__main__":
    setup_database()
