import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

def get_db_connection():
    user = os.getenv("ORACLE_USER")
    password = os.getenv("ORACLE_PASSWORD")
    dsn = os.getenv("ORACLE_DSN")
    
    if not all([user, password, dsn]):
        raise ValueError("Oracle DB connection info is missing in .env")
        
    connection = oracledb.connect(user=user, password=password, dsn=dsn)
    return connection

def setup_database():
    print("Connecting to Oracle DB to setup 17-dimensional table...")
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        # 1. 기존 테이블이 있다면 초기화 (DROP)
        try:
            cursor.execute("DROP TABLE maintenance_history")
            print("Dropped old maintenance_history table.")
        except oracledb.DatabaseError as e:
            pass # 테이블이 없으면 패스
            
        # 2. 새로운 17차원 RAG용 테이블 생성 쿼리
        create_table_sql = """
        CREATE TABLE maintenance_history (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pattern_desc VARCHAR2(255),
            
            -- 17 Core Sensors
            IONGAUGEPRESSURE NUMBER,
            ETCHBEAMVOLTAGE NUMBER,
            ETCHBEAMCURRENT NUMBER,
            ETCHSUPPRESSORVOLTAGE NUMBER,
            ETCHSUPPRESSORCURRENT NUMBER,
            FLOWCOOLFLOWRATE NUMBER,
            FLOWCOOLPRESSURE NUMBER,
            ETCHGASCHANNEL1READBACK NUMBER,
            ETCHPBNGASREADBACK NUMBER,
            FIXTURETILTANGLE NUMBER,
            ROTATIONSPEED NUMBER,
            ACTUALROTATIONANGLE NUMBER,
            FIXTURESHUTTERPOSITION NUMBER,
            ETCHSOURCEUSAGE NUMBER,
            ETCHAUXSOURCETIMER NUMBER,
            ETCHAUX2SOURCETIMER NUMBER,
            ACTUALSTEPDURATION NUMBER,
            
            cause VARCHAR2(255),
            action_taken VARCHAR2(500),
            success_rate NUMBER(5, 2),
            is_false_alarm NUMBER(1) DEFAULT 0
        )
        """
        
        print("Creating new maintenance_history table with 17 sensor columns...")
        cursor.execute(create_table_sql)
        
        # 3. 초기 샘플 데이터 주입 (가상의 17차원 데이터)
        # 실제 환경에서는 과거 이력을 통해 이 값을 채워넣습니다.
        insert_sql = """
        INSERT INTO maintenance_history (
            pattern_desc, IONGAUGEPRESSURE, ETCHBEAMVOLTAGE, ETCHBEAMCURRENT, 
            ETCHSUPPRESSORVOLTAGE, ETCHSUPPRESSORCURRENT, FLOWCOOLFLOWRATE, FLOWCOOLPRESSURE, 
            ETCHGASCHANNEL1READBACK, ETCHPBNGASREADBACK, FIXTURETILTANGLE, ROTATIONSPEED, 
            ACTUALROTATIONANGLE, FIXTURESHUTTERPOSITION, ETCHSOURCEUSAGE, ETCHAUXSOURCETIMER, 
            ETCHAUX2SOURCETIMER, ACTUALSTEPDURATION, 
            cause, action_taken, success_rate, is_false_alarm
        )
        VALUES (
            :1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14, :15, :16, :17, :18,
            :19, :20, :21, :22
        )
        """
        # 정규화된 스케일을 가정하여 가상의 센서 평균값(0 근처) 부여
        sample_data = [
            ("Flowcool Pressure Too High", 0.1, 0.2, -0.1, 0.0, 0.0, 2.5, 3.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, "Pump malfunction", "Replace Flowcool Pump", 0.95, 0),
            ("Flowcool leak", 0.0, 0.0, 0.0, 0.0, 0.0, -2.0, -1.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, "Pipe leakage", "Seal pipe joints", 0.88, 0),
            ("Unknown Sensor Glitch", 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, "Sensor Glitch", "Ignore", 0.99, 1)
        ]
        cursor.executemany(insert_sql, sample_data)
        conn.commit()
        print("Table created and sample data inserted.")

    except Exception as e:
        print(f"Database setup failed: {e}")
    finally:
        if 'cursor' in locals():
            cursor.close()
        if 'conn' in locals():
            conn.close()

if __name__ == "__main__":
    setup_database()
